src/Entity/Pokemon.php
<?php

namespace App\Entity;

use App\Repository\PokemonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PokemonRepository::class)]
#[ORM\Table(name: 'pokemon')]
class Pokemon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToMany(targetEntity: Team::class, inversedBy: 'pokemon')]
    private $team;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private $name_slug;

    #[ORM\Column(type: 'bigint')]
    private $base_experience;

    #[ORM\OneToOne(mappedBy: 'pokemon', targetEntity: Sprite::class, cascade: ['persist', 'remove'])]
    private $sprite;

    #[ORM\ManyToMany(targetEntity: Abilities::class, mappedBy: 'pokemon')]
    private $abilities;

    #[ORM\ManyToMany(targetEntity: Types::class, mappedBy: 'pokemon')]
    private $types;

    public function __construct()
    {
        $this->team = new ArrayCollection();
        $this->abilities = new ArrayCollection();
        $this->types = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Team>
     */
    public function getTeam(): Collection
    {
        return $this->team;
    }

    public function addTeam(Team $team): self
    {
        if (!$this->team->contains($team)) {
            $this->team[] = $team;
        }

        return $this;
    }

    public function removeTeam(Team $team): self
    {
        $this->team->removeElement($team);

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNameSlug(): ?string
    {
        return $this->name_slug;
    }

    public function setNameSlug(string $name_slug): self
    {
        $this->name_slug = $name_slug;

        return $this;
    }

    public function getBaseExperience(): ?string
    {
        return $this->base_experience;
    }

    public function setBaseExperience(string $base_experience): self
    {
        $this->base_experience = $base_experience;

        return $this;
    }

    public function getSprite(): ?Sprite
    {
        return $this->sprite;
    }

    public function setSprite(?Sprite $sprite): self
    {
        // unset the owning side of the relation if necessary
        if ($sprite === null && $this->sprite !== null) {
            $this->sprite->setPokemon(null);
        }

        // set the owning side of the relation if necessary
        if ($sprite !== null && $sprite->getPokemon() !== $this) {
            $sprite->setPokemon($this);
        }

        $this->sprite = $sprite;

        return $this;
    }

    /**
     * @return Collection<int, Abilities>
     */
    public function getAbilities(): Collection
    {
        return $this->abilities;
    }

    public function addAbility(Abilities $ability): self
    {
        if (!$this->abilities->contains($ability)) {
            $this->abilities[] = $ability;
            $ability->addPokemon($this);
        }

        return $this;
    }

    public function removeAbility(Abilities $ability): self
    {
        if ($this->abilities->removeElement($ability)) {
            $ability->removePokemon($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Types>
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Types $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
            $type->addPokemon($this);
        }

        return $this;
    }

    public function removeType(Types $type): self
    {
        if ($this->types->removeElement($type)) {
            $type->removePokemon($this);
        }

        return $this;
    }
}

src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\ManyToMany(targetEntity: Pokemon::class, mappedBy: 'team')]
    private $pokemon;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private \DateTime $creation_date;

    public function __construct(string $teamName)
    {
        $this->pokemon = new ArrayCollection();
        $this->name = $teamName;
        $this->creation_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreationDate(): \DateTime
    {
        return $this->creation_date;
    }

    /**
     * @param \DateTime $creation_date
     */
    public function setCreationDate(\DateTime $creation_date): void
    {
        $this->creation_date = $creation_date;
    }

    /**
     * @return Collection<int, Pokemon>
     */
    public function getPokemon(): Collection
    {
        return $this->pokemon;
    }

    public function addPokemon(Pokemon $pokemon): self
    {
        if (!$this->pokemon->contains($pokemon)) {
            $this->pokemon[] = $pokemon;
            $pokemon->addTeam($this);
        }

        return $this;
    }

    public function removePokemon(Pokemon $pokemon): self
    {
        if ($this->pokemon->removeElement($pokemon)) {
            $pokemon->removeTeam($this);
        }

        return $this;
    }
}

src/Controller/TeamController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use App\Exception\TeamNameValidationException;
use App\Services\TeamService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TeamController extends AbstractController
{
    #[Route("/team/create", name: "team_create")]
    #[Route("/team/create/{id}", name: "team_created")]
    public function index(int $id = null, TeamService $teamService): Response
    {
        return $this->render('team/index.html.twig', [
            'title' => 'Create Team',
            'team' => $id ? $teamService->getTeam($id) : null,
            'pokemons' => $id ? $teamService->getPokemons($id) : []
        ]);
    }

    #[Route("/team/add", name: "team_add", methods: 'POST')]
    public function createTeam(Request $request, TeamService $teamService): JsonResponse
    {
        $teamName = $request->get('name');

        try {
            $team = $teamService->createTeam($teamName);
        }catch (\Exception $e) {
            return new JsonResponse([
                'message' => $e->getMessage()
            ], Response::HTTP_BAD_REQUEST);
        }

        return new JsonResponse([
            'team_name' => $team->getName(),
            'team_id' => $team->getId()
        ], Response::HTTP_CREATED);
    }

    #[Route("/team/{teamId}/add-pokemon", name: "team_add_pokemon")]
    public function addPokemon(int $teamId, TeamService $teamService): JsonResponse
    {
        try {
            $pokemon = $teamService->addPokemonToTeam($teamId);
        }catch (\Exception $e) {
            return new JsonResponse([
                'message' => $e->getMessage()
            ], Response::HTTP_BAD_REQUEST);
        }

        return new JsonResponse([
            'pokemon' => $pokemon->getName()
        ], Response::HTTP_OK);
    }

    #[Route("/team/list", name: "team_list")]
    public function teamList(TeamService $teamService): Response
    {
        $list = $teamService->getAllTeams();

        return $this->render('team/list.html.twig', [
            'title' => 'Team List',
            'list' => $list
        ]);
    }

    #[Route("/team/{teamId}/edit", name: "team_edit")]
    public function editTeam(int $teamId, TeamService $teamService)
    {
        /**
         *@var Team $team
        */
        $team = $teamService->getTeam($teamId);

        return $this->render('team/edit.html.twig', [
            'title' => "Edit team {$team->getName()}",
            'team' => $team,
            'pokemons' => $team->getPokemon()
        ]);
    }

    #[Route("/team/{teamId}/edit/remove-pokemon/{pokemonId}", name: "team_remove_pokemon", methods: 'POST')]
    public function teamRemovePokemon(int $teamId, int $pokemonId, TeamService $teamService): JsonResponse
    {
        try {
            $teamService->removePokemon($teamId, $pokemonId);
        }catch (\Exception $e) {
            return new JsonResponse([
                'message' => $e->getMessage()
            ], Response::HTTP_BAD_REQUEST);
        }

        return new JsonResponse([], Response::HTTP_OK);
    }

    #[Route("/team/{teamId}/edit/change-name", name: "team_change_name", methods: 'POST')]
    public function changeTeamName(int $teamId, TeamService $teamService, Request $request): JsonResponse
    {
        try {
            $teamService->changeTeamName($teamId, $request->get('team_name'));
        }catch (TeamNameValidationException $e) {
            return new JsonResponse([
                'message' => $e->getMessage()
            ], Response::HTTP_BAD_REQUEST);
        }

        return new JsonResponse([], Response::HTTP_OK);
    }
}

templates/team/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label for="team-name" class="input-group-text">Team name</label>
                </div>
                <input id="team-name" name="team-name" type="text" class="form-control" placeholder="Team Name" value="{{ team.name }}">
            </div>
        </div>
        <div class="col-md-6">
            <button class="btn btn-block btn-success" id="save-team-name">Save</button>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-10">

            <table class="table table-striped" id="team-edit-table">
                <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Name</th>
                    <th scope="col">Abilities</th>
                    <th scope="col">Types</th>
                    <th scope="col">Base Experience</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for pokemon in pokemons %}
                    <tr class="row-pokemon-{{ pokemon.id }}">
                        <td>
                            <img src="{{ pokemon.sprite.url }}" width="100" height="100" alt="Pokemon {{ pokemon.name }}">
                        </td>
                        <td>
                            {{ pokemon.name }}
                        </td>
                        <td>
                            {% for ability in pokemon.abilities %}
                            <div class="row">
                                <div class="col-md-12">
                                    {{ ability.name }}
                                </div>
                            </div>
                            {% endfor %}
                        </td>
                        <td>
                            {% for type in pokemon.types %}
                            <div class="row">
                                <div class="col-md-12">
                                {{ type.name }}
                                </div>
                            </div>
                            {% endfor %}
                        </td>
                        <td>
                            {{ pokemon.baseExperience }}
                        </td>
                        <td>
                            <button class="btn btn-danger btn-block remove-pokemon-button" data-pokemon-id="{{ pokemon.id }}">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="col-md-2">
            <button type="button" class="btn btn-primary btn-block" id="add-pokemon">
                <i class="fa-solid fa-circle-plus"></i> Add Pokemon
            </button>
        </div>

    </div>



{% endblock %}

{% block javascripts %}

    <script>
        $(document).on('click', '.remove-pokemon-button', function () {
            let pokemonId = $(this).data('pokemon-id');
            let url = "{{ path('team_remove_pokemon', {'teamId': team.id, 'pokemonId':  "REPLACEME"}) }}";
            $.ajax({
                url: url.replace('REPLACEME', pokemonId),
                method: 'POST',
                data: {
                    'team_id': '{{ team.id }}',
                    'pokemonId': pokemonId
                },
                dataType: 'json',
                success: (response) => {
                    Swal.fire({
                        icon: 'success',
                        title: 'Pokemon Removed'
                    }).then(() => {
                        $('.row-pokemon-' + pokemonId).remove();
                    });
                },
                error: (response) => {
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        html: response.responseJSON.message,
                    });
                }
            });
        }).on('click', '#add-pokemon', function () {
            $.ajax({
                url: ' {{ path("team_add_pokemon", {'teamId': team.id}) }} ',
                type: 'GET',
                success: (response) => {
                    Swal.fire({
                        icon: 'success',
                        title: 'Pokemon Added',
                        html: response.pokemon
                    }).then(() => {
                        window.location.reload();
                    });
                },
                error: (response) => {
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        html: response.responseJSON.message,
                    });
                }
            });
        }).on('click', '#save-team-name', function () {
            $.ajax({
                url: ' {{ path("team_change_name", {'teamId': team.id}) }} ',
                type: 'POST',
                data: {
                    'team_name': $('#team-name').val(),
                },
                dataType: 'json',
                success: (response) => {
                    Swal.fire({
                        icon: 'success',
                        title: 'Team name changed',
                        html: response.pokemon
                    }).then(() => {
                        window.location.reload();
                    });
                },
                error: (response) => {
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        html: response.responseJSON.message,
                    });
                }
            });
        })

    </script>

{% endblock %}

templates/team/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="row justify-content-center mb-5">
        <div class=" col-md-4 team-name-input-container">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label for="team-name" class="input-group-text">Team name</label>
                </div>
                <input id="team-name" name="team-name" type="text" class="form-control" placeholder="Team Name"
                        {% if team.id is defined and team.id is not null %}
                            value="{{ team.name }}"
                            disabled="disabled"
                        {% endif %}
                >
            </div>
        </div>
        {% if team.id is not defined or team.id is null %}
        <div class="col-md-2">
            <button type="button" class="btn btn-primary btn-block" id="add-team">
                Create Team
            </button>
        </div>
        {% endif %}
    </div>

    {% if team.id is defined and team.id is not null %}
        {% include 'team/template/team-table.html.twig' with pokemons %}
    {% endif %}

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(() => {
            $('#add-team').on('click', () => {
                $.ajax({
                    url: '{{ path("team_add") }}',
                    type: 'POST',
                    data: {
                        name: $('#team-name').val()
                    },
                    dataType:'json',
                    success: (response) => {
                        let path = '{{ path("team_created", {'id': 'replacemeasap'}) }}'
                        path = path.replace('replacemeasap', response.team_id);
                        window.location.href = path;
                    },
                    error: (response) => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            html: response.responseJSON.message,
                        });
                    }
                });
            });

            {% if team.id is defined and team.id is not null %}

                $('#add-pokemon').on('click', () => {
                    $.ajax({
                        url: ' {{ path("team_add_pokemon", {'teamId': team.id}) }} ',
                        type: 'GET',
                        success: (response) => {
                            Swal.fire({
                                icon: 'success',
                                title: 'Pokemon Added',
                                html: response.pokemon
                            }).then(() => {
                                window.location.reload();
                            });
                        },
                        error: (response) => {
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                html: response.responseJSON.message,
                            });
                        }
                    });
                });

                $('#team-pokemon-table').DataTable({
                    "bPaginate": false,
                    "bFilter": false,
                });

            {% endif %}
        });
    </script>
{% endblock %}

templates/team/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

    <table id="team-list-table" class="table table-striped" style="width:100%">
        <thead>
        <tr class="text-center">
            <th scope="col">Team Name</th>
            <th scope="col">Pokemons</th>
            <th scope="col">Total Base Experience</th>
            <th scope="col">Types</th>
            <th scope="col">Creation Date</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for team_id, item in list %}
            <tr>
                <td class="text-center" style="width: 20%">
                    <div class="row">
                        <div class="col-md-12">
                        {{ item.team.name }}
                        </div>
                    </div>
                </td>
                <td class="text-center" style="width: 20%">
                    <div class="row">
                    {% set sum_base_experience = 0 %}
                    {% for pokemon in item.pokemon %}
                        {% set sum_base_experience = sum_base_experience + pokemon.baseExperience %}
                        <div class="col-md-4">
                            <img src="{{ pokemon.sprite.url }}" width="50" height="50" alt="Pokemon {{ pokemon.name }}">
                        </div>
                    {% endfor %}
                    </div>
                </td>
                <td class="text-center" style="width: 20%">
                    {{ sum_base_experience }}
                </td>
                <td class="text-center" style="width: 20%">
                    <div class="row">
                    {% for type in item.types %}
                        <div class="col-md-4 text-center" style="min-height: 2rem; border: 1px solid lightgray">{{ type }}</div>
                    {% endfor %}
                    </div>
                </td>
                <td class="text-center" style="width: 20%">
                    {{ item.team.creationDate|date('d/m/Y H:i') }}
                </td>
                <td>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="{{ path('team_edit', {'teamId': team_id}) }}" type="button" class="btn btn-primary btn-block">Edit</a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(() => {
            $('#team-list-table').DataTable({
                "bPaginate": false,
                "columnDefs": [
                    { "searchable": false, "targets": [0, 1, 2, 4] }
                ],
                order: [[4, 'desc']]
            });
        })
    </script>

{% endblock %}